version: '3'
networks:
  bcloud-net:
    external: true
services:
  nginx:
    build: .
    ports:
      - "3000:3000"
    networks:
      - bcloud-net
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
