version: '3'
networks:
  bcloud-net:
    external: true
services:
  db:
    container_name: db_1
    image: mongo:4.4
    ports:
      - "27015:27017"
    volumes:
      - mongo-data:/data/db
    networks:
      - bcloud-net
  app1:
    image: server_app
    container_name: app_1
    build: .
    ports:
      - "3001:3001"
    environment:
      - DB_INIT=false
      - SERVER_PORT=3001
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db
    volumes:
      - store-vol:/app/store
    networks:
      - bcloud-net
  app2:
    image: server_app
    container_name: app_2
    build: .
    ports:
      - "3002:3002"
    environment:
      - DB_INIT=false
      - SERVER_PORT=3002
      - MONGO_URI=mongodb://db:27017
    depends_on:
      - db
    volumes:
      - store-vol:/app/store
    networks:
      - bcloud-net
  nginx:
    build:
      context: .
      dockerfile: Dockerfile.nginx
    ports:
      - "3000:3000"
    networks:
      - bcloud-net
    depends_on:
      - app1
      - app2
    volumes:
      - ./nginx.conf:/etc/nginx/nginx.conf
volumes:
  mongo-data:
  store-vol:
    external: true
